name: Run Postman API Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Rust API
        working-directory: rust-api-example
        run: nohup cargo run > rust-api.log 2>&1 &

      - name: Check Rust API Logs
        run: cat rust-api-example/rust-api.log

      - name: Wait for API to be ready
        run: sleep 60

      - name: Verify API is running
        run: netstat -an | grep 8080

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        working-directory: rust-api-example
        run: newman run collection.json
