name: Run Postman API Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Navigate to Rust project
        run: cd rust-api-example

      - name: Start Rust API
        run: cargo run

      - name: Wait for API to be ready
        run: sleep 10

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run rust-api-example/collection.json

